mkdir -p /home/lxuechen_stanford_edu/scratch/tmp
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/8ce796ad-9960-4186-ad7b-77d903dbd1d6 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/51e42431-2d6d-4662-9745-2a554d5d00da --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/99d48ba9-8c84-4d39-9567-56c53b807c37 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/0811aee7-197b-4e71-a660-ddddd240df35 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/000ffbe7-2550-405d-ae6c-c40a1f976f7a --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/7c4aba24-e833-4a50-a229-24f314dc3e49 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/244ff315-f8c3-439e-86b1-48e02d32f7b7 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-16-512/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/fulltune/distilgpt2-16-512/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/a026c847-73d4-44c5-8590-14a555778879 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/e6945b04-0129-4e22-94db-914f24a65a46 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/90bc9ec6-cbc8-4395-8d05-b8e86ca71e72 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/cf8b5696-37bc-4c8c-96f5-f8d00d58ad12 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/e6e78588-bcb9-4f51-b4c9-8055c06d63cb --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/355e7e72-f1b7-408a-be39-26a65b5a183b --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/64017e7b-0489-48a7-9c98-a0a6842fbac3 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/da65d547-1438-47dd-bc9c-a582c56c145b --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-16-512/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080921/scratchtune/distilgpt2-16-512/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/fa4d5aa3-f906-48c8-a44f-c201b50d1c31 --ignore_global_steps '[]' &
