mkdir -p /home/lxuechen_stanford_edu/scratch/tmp
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/38f396f8-3ee5-481f-afa3-0d3e1ddea444 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/736a723e-6c9d-45a2-bf96-b352a67fb57c &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/0cd1ed92-a296-4ab4-b7cc-4e2e38e37a19 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/e16096cb-ff4c-4c2b-9c92-7eb2c4bd824b &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/496a602c-c7b9-466b-9035-474b241adb42 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/ef42de06-d9e4-4306-9a93-e4dbc271c347 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/e2fe082a-0c05-4a0d-b8f2-3a7946210199 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-16-512/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-16-512/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/8e5d5ae0-759e-4bf5-b8e2-1a26bdb90f86 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/ec56f03c-69ca-41fc-a291-e9b665f012e4 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/3fc65006-d5bd-4dc5-b19a-b57a746c0281 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/9b178251-b18a-4db7-817a-04593c1f18a4 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/bbe5e483-b393-4d20-a34d-d943dfd9d6fd &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/d347fa72-5aad-46fc-8bcb-3df392857960 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/f356cba0-d3d6-4763-80f1-e8d406751677 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/c7fddaec-bdf9-4176-93cc-026a82951d27 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-16-512/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-16-512/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/d1f770cd-56d7-445d-98df-a35130bb5563 &
