mkdir -p /home/lxuechen_stanford_edu/scratch/tmp
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-18-576/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-18-576/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/2cdd1b0c-4fa3-442a-91ab-74a83820d551 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-20-640/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-20-640/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/aa5f15ac-417a-4fff-8f29-08549aaeb42a --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-22-704/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-22-704/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/af1bffce-f710-49ed-8cbc-ca2ef089b53d --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-24-768/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-24-768/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/8a2ab831-801f-43af-9609-8fc18641f590 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-26-832/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-26-832/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/f34c519e-5aa4-4966-b954-405fcf9536aa --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-28-896/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-28-896/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/e20101b8-076a-40ea-a3b1-d3613497ac97 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-30-960/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/fulltune/distilgpt2-30-960/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/0535d042-5c63-439c-92e0-97fd5b5519ff --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-18-576/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-18-576/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/0bbf55d5-5588-44b8-89a8-3f972993148a --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-20-640/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-20-640/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/2626553e-5526-4842-92dc-17eedb841d86 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-22-704/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-22-704/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/989909b9-7222-4ebc-b183-7c37a3c6493e --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-24-768/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-24-768/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/7e2eb01e-5535-43ea-ad28-258b0dfff82d --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-26-832/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-26-832/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/833d0eba-ce47-4e62-9338-4b1f3dad4b36 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-28-896/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-28-896/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/512b7aff-fc3a-4257-bec6-7b5bd22c8c62 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /nlp/scr/lxuechen/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-30-960/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_081221/scratchtune/distilgpt2-30-960/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/cc046dde-3b34-4bcb-ac9d-3936159c342c --ignore_global_steps '[]' &
