mkdir -p /home/lxuechen_stanford_edu/scratch/tmp
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/f7556ef9-a5ad-4597-81f6-90cb4411218f --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/dcaf7a1b-f073-4f38-884d-08a828e5129a --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/cdc752fc-c715-43e7-98b4-3ccbec1c2547 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/d1258756-8da3-49ee-a401-c889ab634868 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/00851795-2a5a-455d-9938-74c173e0f3a1 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/6642a5e1-8af9-414c-b999-49c43b17df3d --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/c50b784c-8b7e-4ddc-b7a4-ecebe68f3658 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-16-512/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-16-512/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/61ecaf2f-d3e5-4e2f-bd94-2ca44d163139 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/0a9834a4-383d-4903-ac32-e4f6cc2e2618 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/019d8bdb-a629-48c2-895d-6dac3a45b678 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/59764bc2-f378-45b9-9ec9-a8b3194fe640 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/77d2e1ad-f70c-49c8-8e4e-3e60bfb0721c --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/8f1ebeb6-5287-45a1-ac72-b40775913072 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/57efd0ec-a10c-4870-b5e7-32b07f758e37 --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/4e1e8e8b-db85-4cd5-903b-553084ac08bd --ignore_global_steps '[]' &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-16-512/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-16-512/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/7088dff1-8107-41eb-8900-c78d11f9347b --ignore_global_steps '[]' &
