mkdir -p /home/lxuechen_stanford_edu/scratch/tmp
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/05007e06-fd4a-48c4-b32b-5caa34c3dd80 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/62b65eb7-e06b-492e-8130-ecfcddbd35cd &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/3d716693-7619-4f26-8cb7-0abfde0914f5 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/d5e93d93-fd81-4bf6-9755-07e28683e736 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/b95fdd70-6688-47ba-a77b-77b74c6aceb1 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/10531fe0-414e-40dd-be92-1bbc52ffdb4c &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/fulltune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/bcc7ec17-1eca-4a09-8630-d12243adeef0 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-2-64/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-2-64/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/3021fbd9-d638-43c5-93fc-197d3342da21 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-4-128/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-4-128/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/2dc48a16-1ee2-4d79-a10d-d913d548c3e7 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-6-192/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-6-192/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/271f048e-87f1-445a-92cf-b54ea9ffdb1c &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-8-256/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-8-256/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/f088b81d-4dab-4c00-84b2-e0e7e3dc8dc7 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-10-320/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-10-320/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/9bec8a4b-1583-4ae3-b55a-2a37429aa7a7 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-12-384/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-12-384/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/40050aab-e4fd-481c-ac1d-3a2900f47af3 &
python -m gpt2stuff.eval.eval_generations --ref_path /home/lxuechen_stanford_edu/data/prefix-tuning/data/e2e_data/clean_references_test.txt --e2e_dir /home/lxuechen_stanford_edu/software/e2e-metrics --task eval_trajectory --gen_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-14-448/generations_model/eval --img_dir /nlp/scr/lxuechen/prefixtune/date_080721/scratchtune/distilgpt2-14-448/generations_score --python True --scratch_dir /home/lxuechen_stanford_edu/scratch/tmp/edb6403b-b5e1-4f90-95ee-e52edb077e5f &
